# Generated by Django 3.2.19 on 2023-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('DRINKS', 'Drinks'), ('RESTAURANTS', 'Restaurants')], default='FOOD', max_length=255),
        ),
    ]
