# Generated by Django 3.2.19 on 2023-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230629_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks'), ('restaurants', 'Restaurants')], default='food', max_length=255),
        ),
    ]
